<a href="https://colab.research.google.com/github/VMOnGit/PythonForML/blob/main/Basic%20Python%20Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Numpy`- Numerical Python

> The python library for basic array operations.

### Basics

This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## `NumPy` Array Attributes

First let's discuss some useful array attributes.

We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.

We'll use `NumPy`'s random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

### Loading `numpy` to a python programme

>Syntax 

```
import numpy as <<"name of instance">>

```

eg: ``` import numpy as np```

## Define different types of `numpy` arrays

In [ ]:
#np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print(x1)

[8 5 4 7 4 1]


In [ ]:
print(x2)

[[3 3 9 2]
 [5 2 3 5]
 [7 2 7 1]]


In [ ]:
print(x3)

[[[6 5 0 0 3]
  [1 9 9 6 6]
  [7 8 8 7 0]
  [8 6 8 9 8]]

 [[3 6 1 7 4]
  [9 2 0 8 2]
  [7 8 4 4 1]
  [7 6 9 4 1]]

 [[5 9 7 1 3]
  [5 7 3 6 6]
  [7 9 1 9 6]
  [0 3 8 4 1]]]


## Attributes of arrays

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
